# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
  host: localhost
  username: pguser
  password: password

development:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
  host: localhost
  username: pguser
  password: password

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
